apiVersion: v1
kind: Secret
metadata:
  name:  nuxt-secret
data:
    NUXT_PUBLIC_FIREBASE_API_KEY: ""
    NUXT_PUBLIC_STRIPE_TEST_SECRET_KEY: ""
    NUXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ""
type: Opaque
