# Generated by Django 5.2.6 on 2025-12-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="address_line_two",
            field=models.CharField(
                blank=True,
                help_text="The second address line for billing such as Address line 2, such as apartment, suite, unit, building, floor, etc.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="address_line",
            field=models.CharField(
                help_text="The main address line for billing such as Address line 1, such as the street, PO Box, or company name.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(default="FR", max_length=100),
        ),
    ]
