# Generated by Django 5.1.4 on 2025-04-26 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporter', models.CharField(choices=[('In house', 'In House'), ('DHL', 'Dhl'), ('Chronopost', 'Chronopost'), ('Colissimo - Livraison standard', 'Colissimo Standard'), ('Colissimo International', 'Colissimo International'), ('Coliposte DOM-TOM', 'Coliposte Dom Tom'), ('Coliposte International', 'Coliposte International'), ('Relais colis', 'Relais Colis'), ('En magasin', 'En Magasin')], default='Chronopost', max_length=150)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('customer_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.customerorder')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('delivered', False)), fields=['delivered'], name='not_delivered')],
            },
        ),
    ]
