# Generated by Django 5.0.4 on 2024-05-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_customerorder_city_alter_customerorder_country'),
        ('shipments', '0004_alter_shipment_transporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='transporter',
            field=models.CharField(choices=[('In house', 'In House'), ('DHL', 'Dhl'), ('Post office', 'Post Office'), ('Chronopost', 'Chronopost')], default='In house', max_length=150),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(condition=models.Q(('delivered', False)), fields=['delivered'], name='not_delivered'),
        ),
    ]
