# Generated by Django 5.0.6 on 2024-06-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_alter_shipment_transporter_shipment_not_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='transporter',
            field=models.CharField(choices=[('In house', 'In House'), ('DHL', 'Dhl'), ('Post office', 'Post Office'), ('Chronopost', 'Chronopost')], default='In house', max_length=150),
        ),
    ]
