# Generated by Django 5.1.6 on 2025-02-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0020_alter_shipment_transporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='transporter',
            field=models.CharField(choices=[('In house', 'In House'), ('DHL', 'Dhl'), ('Chronopost', 'Chronopost'), ('Colissimo - Livraison standard', 'Colissimo Standard'), ('Colissimo International', 'Colissimo International'), ('Coliposte DOM-TOM', 'Coliposte Dom Tom'), ('Coliposte International', 'Coliposte International'), ('Relais colis', 'Relais Colis'), ('En magasin', 'En Magasin')], default='Chronopost', max_length=150),
        ),
    ]
