redis:
  address: "redis://@localhost:6379/0"

endpoints:
  - name: payment
    url: http://127.0.0.1:8000/api/v1/
  - name: stock
    url: http://127.0.0.1:8002/api/v1/
  - name: shipment
    url: http://127.0.0.1:8004/api/v1/

webhooks:
  # - name: null
  #   endpoints: all
  #   url: null
