apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  password: <Password>


---

apiVersion: v1
kind: Secret
metadata:
  name: shop-secret
type: Opaque
data:
  stripe_publishable_key: ""
  stripe_acount: ""
  stripe_api_version: ""
  stripe_locale: ""


---

apiVersion: v1
kind: Secret
metadata:
  name: admin-secret
type: Opaque
data:
  password: <Password>
