apiVersion: v1
kind: Service
metadata:
  name: django-app
spec:
  selector:
    app: django
  ports:
  - port: 8000
    targetPort: 8000


---

apiVersion: v1
kind: Service
metadata:
  name: vite-app
spec:
  selector:
    app: vite-app
  ports:
  - port: 5173
    targetPort: 5173


---

apiVersion: v1
kind: Service
metadata:
  name: admin-app
spec:
  selector:
    app: admin-app
  ports:
  - port: 5175
    targetPort: 5175
