apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    environment: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      environment: prod
  template:
    metadata:
      labels:
        app: redis
        environment: prod
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: password
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
