apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
  labels:
    name: redis-app
    environment: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-app
      environment: prod
  template:
    metadata:
      labels:
        name: redis-app
        environment: prod
    spec:
      containers:
      - image: redis:latest
        name: redis-app
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-app-secret
              key: redis_password
        ports:
        - containerPort: 6379
          name: redis-app-port
        # volumeMounts:
        # - mountPath: /data
        #   name: redis-data
      
      # volumes:
      # - name: redis-data
      #   persistentVolumeClaim:
      #     claimName: redis-pvc
