apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
    environment: prod
spec:
  selector:
    app: redis
    environment: prod
  ports:
  - port: 6379
    targetPort: 6379
