# Generated by Django 5.2.9 on 2025-12-16 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="on_sale_products",
        ),
        migrations.RemoveField(
            model_name="product",
            name="images",
        ),
        migrations.AddField(
            model_name="image",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_images",
                to="shop.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="validity_score",
            field=models.CharField(
                blank=True,
                help_text="Indicates whether the product fulfills all the requirements in order to be displayed on Nuxt without any fundamental issues",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="age_group_category",
            field=models.CharField(
                choices=[("Kid", "Kid"), ("Adult", "Adult")],
                default="Adult",
                help_text="Additional category in order to classify products by age group",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Accessories", "Accessories"),
                    ("Activewear", "Activewear"),
                    ("Bags", "Bags"),
                    ("Bras", "Bras"),
                    ("Denim", "Denim"),
                    ("Dresses", "Dresses"),
                    ("Pants", "Pants"),
                    ("Panties", "Panties"),
                    ("Shoes", "Shoes"),
                    ("Skirts", "Skirts"),
                    ("Shorts", "Shorts"),
                    ("Suits", "Suits"),
                    ("Tops", "Tops"),
                    ("Not attributed", "Not Attributed"),
                    ("Other", "Other"),
                ],
                default="Not attributed",
                help_text="The main category under which the product can be grouped. This allows dynamic product grouping given its category",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(
                choices=[
                    ("Print", "Print"),
                    ("Black", "Black"),
                    ("Beige", "Beige"),
                    ("Brown", "Brown"),
                    ("Camel", "Camel"),
                    ("Charcoal", "Charcoal"),
                    ("Cream", "Cream"),
                    ("Green", "Green"),
                    ("Grey", "Grey"),
                    ("Kaki", "Kaki"),
                    ("Marine", "Marine"),
                    ("Navy", "Navy"),
                    ("Orange", "Orange"),
                    ("Pink", "Pink"),
                    ("Red", "Red"),
                    ("Taupe", "Taupe"),
                    ("White", "White"),
                    ("Yellow", "Yellow"),
                ],
                default="Black",
                help_text="Product available colors",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="display_new",
            field=models.BooleanField(default=False, help_text="Show a product as new"),
        ),
        migrations.AlterField(
            model_name="product",
            name="gender_category",
            field=models.CharField(
                choices=[("Man", "Man"), ("Woman", "Woman"), ("Unisex", "Unisex")],
                default="Unisex",
                help_text="Additional category in order to classify products by gender",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                condition=models.Q(("on_sale", True), ("active", True)),
                fields=["on_sale"],
                name="on_sale_products",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="slug_products"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["created_on"], name="created_on_products"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "active", "-created_on"],
                name="category_active_products",
            ),
        ),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_main_image", True)),
                fields=("product",),
                name="unique_main_image_per_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("sale_price__lt", models.F("unit_price"))),
                name="sale_price_lower_than_unit",
            ),
        ),
    ]
