# Generated by Django 5.1.4 on 2025-03-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender_category',
            field=models.CharField(choices=[('Man', 'Man'), ('Woman', 'Woman'), ('Kid', 'Kid'), ('Not attributed', 'Not Attributed')], default='Not attributed', help_text='Additional category in order to classify products by gender', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Activewear', 'Activewear'), ('Bags', 'Bags'), ('Bras', 'Bras'), ('Denim', 'Denim'), ('Dresses', 'Dresses'), ('Pants', 'Pants'), ('Panties', 'Panties'), ('Shoes', 'Shoes'), ('Skirts', 'Skirts'), ('Shorts', 'Shorts'), ('Suits', 'Suits'), ('Tops', 'Tops'), ('Not attributed', 'Not Attributed'), ('Other', 'Other')], default='Not attributed', help_text='The main category under which the product can be grouped. This allows the grouping of products that fit under the given category', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Print', 'Print'), ('Black', 'Black'), ('Beige', 'Beige'), ('Brown', 'Brown'), ('Camel', 'Camel'), ('Charcoal', 'Charcoal'), ('Cream', 'Cream'), ('Green', 'Green'), ('Grey', 'Grey'), ('Kaki', 'Kaki'), ('Marine', 'Marine'), ('Navy', 'Navy'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Red', 'Red'), ('Taupe', 'Taupe'), ('White', 'White'), ('Yellow', 'Yellow')], default='Black', help_text='Product available colors', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('A-line', 'A-line'), ('Apron', 'Apron'), ('Babydoll', 'Babydoll'), ('Balconette', 'Balconette'), ('Ball gown', 'Ball gown'), ('Bikini', 'Bikini'), ('Blouson', 'Blouson'), ('Bodycon', 'Bodycon'), ('Bodyshort', 'Bodyshort'), ('Bouffont', 'Bouffont'), ('Bralette', 'Bralette'), ('Brazilian', 'Brazilian'), ('Brief', 'Brief'), ('Bubble', 'Bubble'), ('Bullet', 'Bullet'), ('Control brief', 'Control brief'), ('Corset', 'Corset'), ('Drop waist', 'Drop waist'), ('Empire', 'Empire'), ('Front fastening', 'Front fastening'), ('Full cup', 'Full cup'), ('G-String', 'G-String'), ('Half cup', 'Half cup'), ('Halter', 'Halter'), ('Hipster', 'Hipster'), ('Jumper', 'Jumper'), ('Minimizer', 'Minimizer'), ('Not attributed', 'Not attributed'), ('Nursing', 'Nursing'), ('One shoulder', 'One shoulder'), ('Peasant', 'Peasant'), ('Pegged', 'Pegged'), ('Peplum', 'Peplum'), ('Plunge', 'Plunge'), ('Princess', 'Princess'), ('Seamless', 'Seamless'), ('Sheath', 'Sheath'), ('Shift', 'Shift'), ('Shirt', 'Shirt'), ('Sleep bra', 'Sleep bra'), ('Slit', 'Slit'), ('Soft cup', 'Soft cup'), ('Sports', 'Sports'), ('Strapless', 'Strapless'), ('Strapless', 'Strapless'), ('Sun', 'Sun'), ('T-Shirt', 'T-Shirt'), ('Tent', 'Tent'), ('Thong', 'Thong'), ('Trapezoid', 'Trapezoid'), ('Triangle', 'Triangle'), ('Tunic', 'Tunic'), ('Underwire', 'Underwire'), ('V-line', 'V-line'), ('Wired', 'Wired'), ('Wrap', 'Wrap'), ('Yoke', 'Yoke'), ('A-line', 'A-line'), ('Apron', 'Apron'), ('Babydoll', 'Babydoll'), ('Balconette', 'Balconette'), ('Ball gown', 'Ball gown'), ('Bikini', 'Bikini'), ('Blouson', 'Blouson'), ('Bodycon', 'Bodycon'), ('Bodyshort', 'Bodyshort'), ('Bouffont', 'Bouffont'), ('Bralette', 'Bralette'), ('Brazilian', 'Brazilian'), ('Brief', 'Brief'), ('Bubble', 'Bubble'), ('Bullet', 'Bullet'), ('Control brief', 'Control brief'), ('Corset', 'Corset'), ('Drop waist', 'Drop waist'), ('Empire', 'Empire'), ('Front fastening', 'Front fastening'), ('Full cup', 'Full cup'), ('G-String', 'G-String'), ('Half cup', 'Half cup'), ('Halter', 'Halter'), ('Hipster', 'Hipster'), ('Jumper', 'Jumper'), ('Minimizer', 'Minimizer'), ('Not attributed', 'Not attributed'), ('Nursing', 'Nursing'), ('One shoulder', 'One shoulder'), ('Peasant', 'Peasant'), ('Pegged', 'Pegged'), ('Peplum', 'Peplum'), ('Plunge', 'Plunge'), ('Princess', 'Princess'), ('Seamless', 'Seamless'), ('Sheath', 'Sheath'), ('Shift', 'Shift'), ('Shirt', 'Shirt'), ('Sleep bra', 'Sleep bra'), ('Slit', 'Slit'), ('Soft cup', 'Soft cup'), ('Sports', 'Sports'), ('Strapless', 'Strapless'), ('Strapless', 'Strapless'), ('Sun', 'Sun'), ('T-Shirt', 'T-Shirt'), ('Tent', 'Tent'), ('Thong', 'Thong'), ('Trapezoid', 'Trapezoid'), ('Triangle', 'Triangle'), ('Tunic', 'Tunic'), ('Underwire', 'Underwire'), ('V-line', 'V-line'), ('Wired', 'Wired'), ('Wrap', 'Wrap'), ('Yoke', 'Yoke')], default='Not attributed', help_text='Additionnal category that can be used to better classify the product in the database', max_length=100, verbose_name='Sub-category'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
