# Generated by Django 5.2.11 on 2026-02-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_product_age_group_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="age_group_category",
            field=models.CharField(
                choices=[("Kid", "Kid"), ("Adult", "Adult")],
                default="Adult",
                help_text="Additional category in order to classify products by age group",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Accessories", "Accessories"),
                    ("Activewear", "Activewear"),
                    ("Bags", "Bags"),
                    ("Bras", "Bras"),
                    ("Denim", "Denim"),
                    ("Dresses", "Dresses"),
                    ("Pants", "Pants"),
                    ("Panties", "Panties"),
                    ("Shoes", "Shoes"),
                    ("Skirts", "Skirts"),
                    ("Shorts", "Shorts"),
                    ("Suits", "Suits"),
                    ("Tops", "Tops"),
                    ("Not attributed", "Not Attributed"),
                    ("Other", "Other"),
                ],
                default="Not attributed",
                help_text="The main category under which the product can be grouped. This allows dynamic product grouping given its category",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="color",
            field=models.CharField(
                choices=[
                    ("Print", "Print"),
                    ("Black", "Black"),
                    ("Beige", "Beige"),
                    ("Brown", "Brown"),
                    ("Camel", "Camel"),
                    ("Charcoal", "Charcoal"),
                    ("Cream", "Cream"),
                    ("Green", "Green"),
                    ("Grey", "Grey"),
                    ("Kaki", "Kaki"),
                    ("Marine", "Marine"),
                    ("Navy", "Navy"),
                    ("Orange", "Orange"),
                    ("Pink", "Pink"),
                    ("Red", "Red"),
                    ("Taupe", "Taupe"),
                    ("White", "White"),
                    ("Yellow", "Yellow"),
                ],
                default="Black",
                help_text="Product available colors",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="gender_category",
            field=models.CharField(
                choices=[("Man", "Man"), ("Woman", "Woman"), ("Unisex", "Unisex")],
                default="Unisex",
                help_text="Additional category in order to classify products by gender",
                max_length=100,
            ),
        ),
    ]
