# Generated by Django 5.0.6 on 2024-07-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_product_category_alter_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Activewear', 'Activewear'), ('Bags', 'Bags'), ('Bras', 'Bras'), ('Denim', 'Denim'), ('Dresses', 'Dresses'), ('Pants', 'Pants'), ('Panties', 'Panties'), ('Shoes', 'Shoes'), ('Skirts', 'Skirts'), ('Shorts', 'Shorts'), ('Suits', 'Suits'), ('Tops', 'Tops'), ('Not attributed', 'Not Attributed'), ('Other', 'Other')], default='Not attributed', help_text='The main category under which the product can be grouped. This allows the grouping of products that fit under the given category', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Print', 'Print'), ('Black', 'Black'), ('Beige', 'Beige'), ('Brown', 'Brown'), ('Camel', 'Camel'), ('Charcoal', 'Charcoal'), ('Cream', 'Cream'), ('Green', 'Green'), ('Grey', 'Grey'), ('Kaki', 'Kaki'), ('Marine', 'Marine'), ('Navy', 'Navy'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Red', 'Red'), ('Taupe', 'Taupe'), ('White', 'White'), ('Yellow', 'Yellow')], default='Black', help_text='Product available colors', max_length=100),
        ),
    ]
