# Generated by Django 5.1.4 on 2025-01-10 14:08

import shop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_model_height_product_model_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_on'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Activewear', 'Activewear'), ('Bags', 'Bags'), ('Bras', 'Bras'), ('Denim', 'Denim'), ('Dresses', 'Dresses'), ('Pants', 'Pants'), ('Panties', 'Panties'), ('Shoes', 'Shoes'), ('Skirts', 'Skirts'), ('Shorts', 'Shorts'), ('Suits', 'Suits'), ('Tops', 'Tops'), ('Not attributed', 'Not Attributed'), ('Other', 'Other')], default='Not attributed', help_text='The main category under which the product can be grouped. This allows the grouping of products that fit under the given category', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Print', 'Print'), ('Black', 'Black'), ('Beige', 'Beige'), ('Brown', 'Brown'), ('Camel', 'Camel'), ('Charcoal', 'Charcoal'), ('Cream', 'Cream'), ('Green', 'Green'), ('Grey', 'Grey'), ('Kaki', 'Kaki'), ('Marine', 'Marine'), ('Navy', 'Navy'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Red', 'Red'), ('Taupe', 'Taupe'), ('White', 'White'), ('Yellow', 'Yellow')], default='Black', help_text='Product available colors', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_height',
            field=models.CharField(blank=True, help_text='Indicates the height of the model wearing the piece of clothing', max_length=100, null=True, validators=[shop.validators.validate_model_height]),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_size',
            field=models.CharField(blank=True, help_text='Indicates the size of the clothe weared by the model', max_length=100, null=True),
        ),
    ]
