# Generated by Django 4.0.1 on 2022-03-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0004_alter_additionalvariant_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Coats', 'Coats'), ('Dresses', 'Dresses'), ('Lingerie', 'Lingerie'), ('Pants', 'Pants'), ('Shorts', 'Shorts'), ('Skirts', 'Skirts')], default='Skirts', max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('illustration', models.ImageField(blank=True, null=True, upload_to='')),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, to='shop.Product')),
            ],
        ),
    ]
