# Generated by Django 4.1.3 on 2023-12-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='subcategory_slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Activewear', 'Activewear'), ('Bags', 'Bags'), ('Bras', 'Bras'), ('Denim', 'Denim'), ('Dresses', 'Dresses'), ('Pants', 'Pants'), ('Panties', 'Panties'), ('Shoes', 'Shoes'), ('Shorts', 'Shorts'), ('Suits', 'Suits'), ('Tops', 'Tops')], default='Shorts', help_text='Global category for the given collection', max_length=100),
        ),
        migrations.AlterField(
            model_name='collection',
            name='illustration',
            field=models.ImageField(blank=True, help_text='Image size should be 1200x800', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='collection',
            name='sub_category',
            field=models.CharField(choices=[('A-line', 'A-line'), ('Apron', 'Apron'), ('Babydoll', 'Babydoll'), ('Balconette', 'Balconette'), ('Ball gown', 'Ball gown'), ('Bikini', 'Bikini'), ('Blouson', 'Blouson'), ('Bodycon', 'Bodycon'), ('Bodyshort', 'Bodyshort'), ('Bouffont', 'Bouffont'), ('Bralette', 'Bralette'), ('Brazilian', 'Brazilian'), ('Brief', 'Brief'), ('Bubble', 'Bubble'), ('Bullet', 'Bullet'), ('Control brief', 'Control brief'), ('Corset', 'Corset'), ('Drop waist', 'Drop waist'), ('Empire', 'Empire'), ('Front fastening', 'Front fastening'), ('Full cup', 'Full cup'), ('G-String', 'G-String'), ('Half cup', 'Half cup'), ('Halter', 'Halter'), ('Hipster', 'Hipster'), ('Jumper', 'Jumper'), ('Minimizer', 'Minimizer'), ('Not attributed', 'Not attributed'), ('Nursing', 'Nursing'), ('One shoulder', 'One shoulder'), ('Peasant', 'Peasant'), ('Pegged', 'Pegged'), ('Peplum', 'Peplum'), ('Plunge', 'Plunge'), ('Princess', 'Princess'), ('Seamless', 'Seamless'), ('Sheath', 'Sheath'), ('Shift', 'Shift'), ('Shirt', 'Shirt'), ('Sleep bra', 'Sleep bra'), ('Slit', 'Slit'), ('Soft cup', 'Soft cup'), ('Sports', 'Sports'), ('Strapless', 'Strapless'), ('Strapless', 'Strapless'), ('Sun', 'Sun'), ('T-Shirt', 'T-Shirt'), ('Tent', 'Tent'), ('Thong', 'Thong'), ('Trapezoid', 'Trapezoid'), ('Triangle', 'Triangle'), ('Tunic', 'Tunic'), ('Underwire', 'Underwire'), ('V-line', 'V-line'), ('Wired', 'Wired'), ('Wrap', 'Wrap'), ('Yoke', 'Yoke'), ('A-line', 'A-line'), ('Apron', 'Apron'), ('Babydoll', 'Babydoll'), ('Balconette', 'Balconette'), ('Ball gown', 'Ball gown'), ('Bikini', 'Bikini'), ('Blouson', 'Blouson'), ('Bodycon', 'Bodycon'), ('Bodyshort', 'Bodyshort'), ('Bouffont', 'Bouffont'), ('Bralette', 'Bralette'), ('Brazilian', 'Brazilian'), ('Brief', 'Brief'), ('Bubble', 'Bubble'), ('Bullet', 'Bullet'), ('Control brief', 'Control brief'), ('Corset', 'Corset'), ('Drop waist', 'Drop waist'), ('Empire', 'Empire'), ('Front fastening', 'Front fastening'), ('Full cup', 'Full cup'), ('G-String', 'G-String'), ('Half cup', 'Half cup'), ('Halter', 'Halter'), ('Hipster', 'Hipster'), ('Jumper', 'Jumper'), ('Minimizer', 'Minimizer'), ('Not attributed', 'Not attributed'), ('Nursing', 'Nursing'), ('One shoulder', 'One shoulder'), ('Peasant', 'Peasant'), ('Pegged', 'Pegged'), ('Peplum', 'Peplum'), ('Plunge', 'Plunge'), ('Princess', 'Princess'), ('Seamless', 'Seamless'), ('Sheath', 'Sheath'), ('Shift', 'Shift'), ('Shirt', 'Shirt'), ('Sleep bra', 'Sleep bra'), ('Slit', 'Slit'), ('Soft cup', 'Soft cup'), ('Sports', 'Sports'), ('Strapless', 'Strapless'), ('Strapless', 'Strapless'), ('Sun', 'Sun'), ('T-Shirt', 'T-Shirt'), ('Tent', 'Tent'), ('Thong', 'Thong'), ('Trapezoid', 'Trapezoid'), ('Triangle', 'Triangle'), ('Tunic', 'Tunic'), ('Underwire', 'Underwire'), ('V-line', 'V-line'), ('Wired', 'Wired'), ('Wrap', 'Wrap'), ('Yoke', 'Yoke')], default=('Not attributed', 'Not attributed'), help_text='Specific detailled category for the given collection', max_length=100),
        ),
    ]
