# Generated by Django 5.0.4 on 2024-05-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Activewear', 'Activewear'), ('Bags', 'Bags'), ('Bras', 'Bras'), ('Denim', 'Denim'), ('Dresses', 'Dresses'), ('Pants', 'Pants'), ('Panties', 'Panties'), ('Shoes', 'Shoes'), ('Shorts', 'Shorts'), ('Suits', 'Suits'), ('Tops', 'Tops')], default='Shorts', help_text='Global category for the given collection', max_length=100),
        ),
    ]
