# Generated by Django 6.0.3 on 2026-05-10 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text="Unique session identifier which is essentially used for identifying an anonymous user's cart", max_length=400)),
                ('order_reference', models.CharField(blank=True, help_text='A customer order reference which can be used to link a cart item to an order', max_length=100, null=True)),
                ('items', models.JSONField(default=dict)),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('total', models.FloatField(default=0.0)),
                ('payment_intent', models.CharField(blank=True, help_text='Stripe payment intent ID used to identify the payment associated with this cart', max_length=200, null=True)),
                ('is_stale', models.BooleanField(default=False, help_text='Previous products from an authenticated user on which no actions were performed')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_paid_for', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Identifies a logged in user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'ordering': ['-created_on', '-pk'],
                'abstract': False,
                'indexes': [models.Index(condition=models.Q(('is_paid_for', True)), fields=['is_paid_for'], name='is_paid_for_carts')],
            },
        ),
    ]
