# Generated by Django 5.2.6 on 2025-12-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="product",
            new_name="items",
        ),
        migrations.RenameField(
            model_name="cart",
            old_name="price",
            new_name="total",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="size",
        ),
        migrations.AddField(
            model_name="cart",
            name="quantity",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
