# Generated by Django 5.2.6 on 2025-12-25 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_rename_product_cart_items_rename_price_cart_total_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cart",
            name="cart_price_over_zero",
        ),
    ]
