# Generated by Django 5.2.6 on 2025-12-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_remove_cart_cart_price_over_zero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="total",
            field=models.FloatField(default=0.0),
        ),
    ]
