apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-cart
  labels:
    name: django-cart
spec:
  selector:
    matchLabels:
      name: django-cart
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: django-cart
    spec:
      containers:
      - image: postgres:latest
        name: django-cart-db
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-cart-secret
              key: postgres_password

      - image: dpage/pgadmin4
        name: django-cart-pgadmin
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            configMapKeyRef:
              name: django-cart-configmap
              key: pgadmin_default_email
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-cart-secret
              key: pgadmin_default_password 
        - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
          valueFrom:
            configMapKeyRef:
              name: django-cart-configmap
              key: pgadmin_cookie_protection
          

      # - image: django_cart_image
      #   name: django-cart
      #   resources:
      #     requests:
      #       cpu: "20m"
      #       memory: "55M"
      #     limits:
      #       memory: "128Mi"
      #       cpu: "500m"
      #   livenessProbe:
      #     httpGet:
      #       path: /_status/healthz
      #       port: 5000
      #     initialDelaySeconds: 90
      #     timeoutSeconds: 10
      #   readinessProbe:
      #     httpGet:
      #       path: /_status/healthz
      #       port: 5000
      #     initialDelaySeconds: 30
      #     timeoutSeconds: 10
      #   env:
      #   - name: ENVVARNAME
      #     value: ENVVARVALUE
      #   ports:
      #   - containerPort: 5000
      #     name: django-cart
      #   volumeMounts:
      #   - mountPath: /data
      #     name: django-cart-volume

      volumes:
      - name: django-cart-volume
        emptyDir: {}
      restartPolicy: Always
