apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-depl
spec:
  selector:
    matchLabels:
      app: admin-app
  template:
    metadata:
      labels:
        app: admin-app
    spec:
      volumes:
        - name: admin-storage
          persistentVolumeClaim:
            claimName: django-pvc
      containers:
      - name: admin-app
        image: node:latest
        imagePullPolicy: Always
        env:
        - name: VITE_STRIPE_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              key: admin-secret
              name: admin-Secret
        - name: VITE_STRIPE_ACCOUNT
          valueFrom:
            secretKeyRef:
              key: admin-secret
              name: admin-Secret
        - name: VITE_API_VERSION
          value: "2024-06-20"
        - name: VITE_STRIPE_LOCALE
          value: fr
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5174
          name: quasar-port
