apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    app: pgadmin
    environment: prod
spec:
  selector:
    app: pgadmin
    environment: prod
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
