# Generated by Django 5.1.4 on 2025-04-26 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(blank=True, help_text='The token that identifies the customer in Stripe e.g. cus_1234', max_length=100, null=True)),
                ('source_id', models.CharField(blank=True, help_text="The token that identifies the customer's payment method in Stripe e.g. card_1234", max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('address_line', models.CharField(max_length=100)),
                ('zip_code', models.PositiveIntegerField()),
                ('country', models.CharField(default='France', max_length=100)),
                ('city', models.CharField(default='Nord', max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.IntegerField(choices=[(1, 'Woman'), (2, 'Man')], default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
