# Generated by Django 5.0.6 on 2024-07-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_created_on_address_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='address_line',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Nord', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='France', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='firstname',
            field=models.CharField(default='Salomé', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='gender',
            field=models.CharField(choices=[(1, 'Woman'), (2, 'Man')], default=1, max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='lastname',
            field=models.CharField(default='Vargo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
