# Generated by Django 5.0.6 on 2024-07-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_address_address_address_line_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Woman'), (2, 'Man')], default=1, max_length=100),
        ),
    ]
