# Generated by Django 5.0.6 on 2024-07-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_address_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='source_id',
            field=models.CharField(blank=True, help_text="The token that identifies the customer's payment method in Stripe e.g. cus_1234", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stripe_id',
            field=models.CharField(blank=True, help_text='The token that identifies the customer in Stripe e.g. cus_1234', max_length=100, null=True),
        ),
    ]
