# Generated by Django 5.0.6 on 2024-12-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_source_id_alter_userprofile_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='source_id',
            field=models.CharField(blank=True, help_text="The token that identifies the customer's payment method in Stripe e.g. card_1234", max_length=100, null=True),
        ),
    ]
