# Generated by Django 4.1.3 on 2023-11-18 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporter', models.CharField(choices=[('In house', 'In House'), ('DHL', 'Dhl'), ('Post office', 'Post Office'), ('Chronopost', 'Chronopost')], default='In house', max_length=150)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('customer_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.customerorder')),
            ],
        ),
    ]
