# Generated by Django 4.1.3 on 2023-12-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='transporter',
            field=models.CharField(choices=[('In house', 'In House'), ('DHL', 'Dhl'), ('Post office', 'Post Office'), ('Chronopost', 'Chronopost')], default='In house', max_length=150),
        ),
    ]
