# Generated by Django 4.0.1 on 2022-04-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_alter_shipment_transporter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='transporter',
            field=models.CharField(choices=[('In house', 'In House'), ('DHL', 'Dhl'), ('Post office', 'Post Office'), ('Chronopost', 'Chronopost')], default='In house', max_length=150),
        ),
    ]
