# Generated by Django 4.0.1 on 2022-04-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0002_alter_size_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='sub_category',
            field=models.CharField(choices=[('Bra size', 'Bra Size'), ('Clothe size', 'Clothe Size'), ('Not attributed', 'Not Attributed'), ('Shoe size', 'Shoe Size')], default='Clothe size', max_length=100),
        ),
    ]
