# Generated by Django 5.0.6 on 2024-06-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0006_alter_size_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='sub_category',
            field=models.CharField(choices=[('Bra size', 'Bra Size'), ('Clothe size', 'Clothe Size'), ('Not attributed', 'Not Attributed'), ('Shoe size', 'Shoe Size')], default='Clothe size', help_text='Variant specific for product type', max_length=100),
        ),
    ]
