# Generated by Django 5.0.6 on 2024-07-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_address_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Woman'), (2, 'Man')], default=1),
        ),
    ]
