apiVersion: apps/v1
kind: Deployment
metadata:
  name: mystore-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mystore-depl
  template:
    metadata:
      labels:
        app: mystore-depl
    spec:
      containers:

        - name: mystore
          image: mycommerce-mystore:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: mystore-config
            - secretRef:
                name: mystore-secret

        - name: redis
          image: redis:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 6379

        - name: db
          image: mycommerce-db:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mystore-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: mystore-config
                  key: DB_USER
            - name: POSTGRES_DB 
              valueFrom:
                configMapKeyRef:
                  name: mystore-config
                  key: DB_NAME
                
