apiVersion: v1
kind: Secret
metadata:
  name: mystore-secret
data:
  AWS_S3_ACCESS_KEY_ID: ""
  AWS_S3_SECRET_ACCESS_KEY: ""
  DB_PASSWORD: "dG91cGFyZXQ="
  EMAIL_HOST_PASSWORD: ""
  POSTGRES_PASSWORD: "dG91cGFyZXQ="
  PY_UTILITIES_JWT_SECRET: "dGhpc2lzYXBhc3N3b3Jk"
  RABBITMQ_PASSWORD: "Z3Vlc3Q="
  REDIS_PASSWORD: ""
  SECRET_KEY: RWIwUjhXYnhoUTNPd0hNSzV1QzJ2MVZTdnlzVFdzeEoxZDN0Y0ZhbTEwZ29pWUFFY0NxRUNSZ2JLeEI3dUZBWQ==
  STRIPE_PRODUCTION_SECRET_KEY: ""
  STRIPE_TEST_SECRET_KEY: ""
type: Opaque
