kind: Service
apiVersion: v1
metadata:
  name: mystore-serv
spec:
  selector:
    app: mystore-depl # Pod to target
  type: NodePort
  ports:
  - name:  mystore-port
    port:  80
    targetPort:  8000 # Container to expose
    nodePort: 31000
