import { library } from '@fortawesome/fontawesome-svg-core'
import { faCcMastercard, faCcVisa, faFacebookF, faInstagram, faTiktok, faTwitter } from '@fortawesome/free-brands-svg-icons'
import { faHeart as farHeart } from '@fortawesome/free-regular-svg-icons'
import { faEnvelope, faComment, faCircleCheck, faUser, faPen, faFlag, faArrowUp, faArrowRight, faHeart, faEllipsisVertical, faCaretDown, faCaretUp, faFilter, faArrowDown, faImage, faStar, faShoppingBag, faCartShopping, faTableCellsLarge, faTableCells, faShop, faTruck, faTrash, faArrowLeft, faRightFromBracket, faCaretLeft, faAngleLeft, faHome, faPhone, faClockRotateLeft, faMagnifyingGlass, faSignIn, faRightToBracket, faCog, faSliders, faClose, faCaretRight } from '@fortawesome/free-solid-svg-icons'

library.add(faArrowUp)
library.add(faArrowRight)
library.add(faArrowLeft)
library.add(faAngleLeft)
library.add(faArrowDown)
library.add(faComment)
library.add(faCircleCheck)
library.add(faCcVisa)
library.add(faClose)
library.add(faCaretDown)
library.add(faCcMastercard)
library.add(faCaretRight)
library.add(faCaretLeft)
library.add(faCartShopping)
library.add(faCaretDown)
library.add(faCaretUp)
library.add(faEllipsisVertical)
library.add(faEnvelope)
library.add(faFlag)
library.add(faFilter)
library.add(faFacebookF)
library.add(faHeart)
library.add(faHome)
library.add(farHeart)
library.add(faInstagram)
library.add(faImage)
library.add(faRightToBracket)
library.add(faRightFromBracket)
library.add(faShop)
library.add(faShoppingBag)
library.add(faTiktok)
library.add(faPhone)
library.add(faPen)
library.add(faSignIn)
library.add(faStar)
library.add(faCog)
library.add(faSliders)
library.add(faTableCellsLarge)
library.add(faTableCells)
library.add(faTwitter)
library.add(faTruck)
library.add(faTrash)
library.add(faUser)
library.add(faClockRotateLeft)
library.add(faMagnifyingGlass)
