bases:
  - ../../mystore

namespace: dev

resources:
  - configmap.yaml
  
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: mystore-depl
      spec:
        template:
          spec:
            containers:
              - name: mystore
                env:
                  - name: DEBUG
                    value: "True"
