version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
handlers:
  stderr:
    class: logging.StreamHandler
    formatter: standard
    level: DEBUG
    stream: "ext://sys.stderr"
  file:
    class: logging.handlers.RotatingFileHandler
    filename: "apiauthentication.log"
    formatter: standard
    level: DEBUG
    maxBytes: 20000000
    backupCount: 3
loggers:
  root:
    handlers:
      - stderr
      - file
    level: DEBUG
    propagate: true
