# Generated by Django 5.1.4 on 2025-01-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_customerorder_city_alter_customerorder_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='stock_updated',
            field=models.BooleanField(default=False, help_text='Flag that prevents multiple updates of a stock instance with the same customer order reference'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='city',
            field=models.CharField(choices=[('Lille', 'Lille'), ('Paris', 'Paris')], default='Lille', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='country',
            field=models.CharField(choices=[('France', 'France'), ('Guadeloupe', 'Guadeloupe'), ('Martinique', 'Martinique'), ('Monaco', 'Monaco'), ('Réunion', 'Reunion')], default='France', max_length=100),
        ),
    ]
