# Generated by Django 5.1.4 on 2025-02-25 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='The name of the size to use', max_length=100)),
                ('metric', models.CharField(choices=[('Bra', 'Bra'), ('Clothe', 'Clothe'), ('Shoe', 'Shoe'), ('Metric', 'Metric'), ('Text', 'Text')], default='Clothe', help_text='The specific metric to use for the size value', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
                'constraints': [models.UniqueConstraint(fields=('product', 'name'), name='unique_size_per_product')],
            },
        ),
    ]
