# Generated by Django 5.2.10 on 2026-01-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variants", "0003_alter_size_metric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="size",
            name="metric",
            field=models.CharField(
                choices=[
                    ("Bra", "Bra"),
                    ("Clothe", "Clothe"),
                    ("Shoe", "Shoe"),
                    ("Metric", "Metric"),
                    ("Text", "Text"),
                ],
                default="Clothe",
                help_text="The specific metric to use for the size value",
                max_length=100,
            ),
        ),
    ]
