# Generated by Django 5.1.4 on 2025-02-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0019_alter_size_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='size',
            name='metric',
            field=models.CharField(choices=[('Bra', 'Bra'), ('Clothe', 'Clothe'), ('Shoe', 'Shoe'), ('Metric', 'Metric'), ('Text', 'Text')], default='Clothe', help_text='The specific metric to use for the size value', max_length=100),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(help_text='The name of the size to use', max_length=100),
        ),
    ]
