# Generated by Django 5.1.6 on 2025-02-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0020_remove_size_sub_category_size_metric_alter_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='metric',
            field=models.CharField(choices=[('Bra', 'Bra'), ('Clothe', 'Clothe'), ('Shoe', 'Shoe'), ('Metric', 'Metric'), ('Text', 'Text')], default='Clothe', help_text='The specific metric to use for the size value', max_length=100),
        ),
    ]
