# Generated by Django 5.1.4 on 2025-09-09 14:15

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField(blank=True, help_text='Active reference to the product in the catalog and which points to myshop.shop.Product ID field', null=True)),
                ('serialized_data', models.JSONField(default=dict, help_text='Serialized product data')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Price at the time of order', max_digits=5)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('stripe_charge', models.CharField(help_text='The stripe order reference or charge e.g. ch_1234', max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('Lille', 'Lille'), ('Paris', 'Paris')], default='Lille', max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('France', 'France'), ('Guadeloupe', 'Guadeloupe'), ('Martinique', 'Martinique'), ('Monaco', 'Monaco'), ('Réunion', 'Reunion')], default='France', max_length=100)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=5000, null=True)),
                ('completed', models.BooleanField(default=False, help_text='Indicates that the order was fully completed: packaged, shipped and received by the customer')),
                ('refund_requested', models.BooleanField(default=False, help_text='Indicates that the order was cancelled and refund was requested')),
                ('stock_updated', models.BooleanField(default=False, help_text='Flag that prevents multiple updates of a stock instance with the same customer order reference')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, help_text='Reference to the products that were bought at the price at which they were bought on the purchase date', to='orders.product')),
            ],
            options={
                'verbose_name': 'customer order',
                'verbose_name_plural': 'customer orders',
                'ordering': ['-created_on'],
                'indexes': [models.Index(models.Q(('stock_updated', False)), name='stock_not_updated_index')],
            },
        ),
    ]
