# Generated by Django 5.2.6 on 2025-12-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_customerorder_city_alter_customerorder_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerorder",
            name="city",
            field=models.CharField(
                choices=[("Lille", "Lille"), ("Paris", "Paris")],
                default="Lille",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="customerorder",
            name="country",
            field=models.CharField(
                choices=[
                    ("France", "France"),
                    ("Guadeloupe", "Guadeloupe"),
                    ("Martinique", "Martinique"),
                    ("Monaco", "Monaco"),
                    ("Réunion", "Reunion"),
                ],
                default="France",
                max_length=100,
            ),
        ),
    ]
