# Generated by Django 5.2.6 on 2025-12-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_customerorder_city_alter_customerorder_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerorder",
            name="products",
        ),
        migrations.AddField(
            model_name="product",
            name="customer_order",
            field=models.ManyToManyField(
                blank=True,
                help_text="Link to the customer order(s)",
                to="orders.customerorder",
            ),
        ),
        migrations.AlterField(
            model_name="customerorder",
            name="city",
            field=models.CharField(
                choices=[("Lille", "Lille"), ("Paris", "Paris")],
                default="Lille",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="customerorder",
            name="country",
            field=models.CharField(
                choices=[
                    ("France", "France"),
                    ("Guadeloupe", "Guadeloupe"),
                    ("Martinique", "Martinique"),
                    ("Monaco", "Monaco"),
                    ("Réunion", "Reunion"),
                ],
                default="France",
                max_length=100,
            ),
        ),
    ]
