# Generated by Django 5.2.6 on 2025-12-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_alter_customerorder_city_alter_customerorder_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerorder",
            name="city",
            field=models.CharField(
                choices=[("Lille", "Lille"), ("Paris", "Paris")],
                default="Lille",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="customerorder",
            name="country",
            field=models.CharField(
                choices=[
                    ("France", "France"),
                    ("Guadeloupe", "Guadeloupe"),
                    ("Martinique", "Martinique"),
                    ("Monaco", "Monaco"),
                    ("Réunion", "Reunion"),
                ],
                default="France",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="customerorder",
            name="total",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.FloatField(
                default=0.0, help_text="Price at the time of order"
            ),
        ),
    ]
