# Generated by Django 4.0.3 on 2022-03-08 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.utils
import shop.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='XQNTFsn1dmCL', max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Size', 'Size')], default='Size', max_length=100)),
                ('sub_category', models.CharField(choices=[('Not attributed', 'Not Attributed'), ('Shoe size', 'Shoe Size'), ('Bra size', 'Bra Size')], default='Not attributed', max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Used for the image's alt attribute", max_length=100, unique=True)),
                ('variant', models.CharField(blank=True, max_length=100, null=True)),
                ('original', models.ImageField(upload_to=shop.utils.image_path)),
                ('is_main_image', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='Ff8WFPsFUw', max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('Black', 'Black'), ('Beige', 'Beige'), ('Camel', 'Camel'), ('Charcoal', 'Charcoal'), ('Cream', 'Cream'), ('Green', 'Green'), ('Grey', 'Grey'), ('Marine', 'Marine'), ('Navy', 'Navy'), ('Red', 'Red'), ('Taupe', 'Taupe'), ('White', 'White'), ('Yellos', 'Yellow')], default='Black', help_text='Defines a declination of a main product in color', max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, default=1, help_text='Cost price of the product', max_digits=5, validators=[shop.validators.price_validator])),
                ('sale_value', models.PositiveIntegerField(default=0)),
                ('on_sale', models.BooleanField(default=False)),
                ('display_new', models.BooleanField(default=False, help_text='Explicitly mark a product as being new')),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=False)),
                ('modified_on', models.DateField(auto_now_add=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('additional_variants', models.ManyToManyField(blank=True, help_text='Declination in size, patterns...', to='shop.additionalvariant')),
                ('images', models.ManyToManyField(blank=True, to='shop.image')),
            ],
            options={
                'ordering': ['name', '-created_on'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Used for the video alt attribute', max_length=100, unique=True)),
                ('content', models.FileField(upload_to=shop.utils.video_path, validators=[shop.validators.validate_video_file_extension])),
                ('created_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('products', models.ManyToManyField(blank=True, to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.video'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['original'], name='shop_image_origina_a845c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_list_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'reference'], name='shop_produc_name_68978c_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'color'), name='unique_name_with_color'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user',), name='one_list_per_user'),
        ),
    ]
