# Generated by Django 4.1.3 on 2023-12-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('A-line', 'A-line'), ('Apron', 'Apron'), ('Babydoll', 'Babydoll'), ('Balconette', 'Balconette'), ('Ball gown', 'Ball gown'), ('Bikini', 'Bikini'), ('Blouson', 'Blouson'), ('Bodycon', 'Bodycon'), ('Bodyshort', 'Bodyshort'), ('Bouffont', 'Bouffont'), ('Bralette', 'Bralette'), ('Brazilian', 'Brazilian'), ('Brief', 'Brief'), ('Bubble', 'Bubble'), ('Bullet', 'Bullet'), ('Control brief', 'Control brief'), ('Corset', 'Corset'), ('Drop waist', 'Drop waist'), ('Empire', 'Empire'), ('Front fastening', 'Front fastening'), ('Full cup', 'Full cup'), ('G-String', 'G-String'), ('Half cup', 'Half cup'), ('Halter', 'Halter'), ('Hipster', 'Hipster'), ('Jumper', 'Jumper'), ('Minimizer', 'Minimizer'), ('Not attributed', 'Not attributed'), ('Nursing', 'Nursing'), ('One shoulder', 'One shoulder'), ('Peasant', 'Peasant'), ('Pegged', 'Pegged'), ('Peplum', 'Peplum'), ('Plunge', 'Plunge'), ('Princess', 'Princess'), ('Seamless', 'Seamless'), ('Sheath', 'Sheath'), ('Shift', 'Shift'), ('Shirt', 'Shirt'), ('Sleep bra', 'Sleep bra'), ('Slit', 'Slit'), ('Soft cup', 'Soft cup'), ('Sports', 'Sports'), ('Strapless', 'Strapless'), ('Strapless', 'Strapless'), ('Sun', 'Sun'), ('T-Shirt', 'T-Shirt'), ('Tent', 'Tent'), ('Thong', 'Thong'), ('Trapezoid', 'Trapezoid'), ('Triangle', 'Triangle'), ('Tunic', 'Tunic'), ('Underwire', 'Underwire'), ('V-line', 'V-line'), ('Wired', 'Wired'), ('Wrap', 'Wrap'), ('Yoke', 'Yoke'), ('A-line', 'A-line'), ('Apron', 'Apron'), ('Babydoll', 'Babydoll'), ('Balconette', 'Balconette'), ('Ball gown', 'Ball gown'), ('Bikini', 'Bikini'), ('Blouson', 'Blouson'), ('Bodycon', 'Bodycon'), ('Bodyshort', 'Bodyshort'), ('Bouffont', 'Bouffont'), ('Bralette', 'Bralette'), ('Brazilian', 'Brazilian'), ('Brief', 'Brief'), ('Bubble', 'Bubble'), ('Bullet', 'Bullet'), ('Control brief', 'Control brief'), ('Corset', 'Corset'), ('Drop waist', 'Drop waist'), ('Empire', 'Empire'), ('Front fastening', 'Front fastening'), ('Full cup', 'Full cup'), ('G-String', 'G-String'), ('Half cup', 'Half cup'), ('Halter', 'Halter'), ('Hipster', 'Hipster'), ('Jumper', 'Jumper'), ('Minimizer', 'Minimizer'), ('Not attributed', 'Not attributed'), ('Nursing', 'Nursing'), ('One shoulder', 'One shoulder'), ('Peasant', 'Peasant'), ('Pegged', 'Pegged'), ('Peplum', 'Peplum'), ('Plunge', 'Plunge'), ('Princess', 'Princess'), ('Seamless', 'Seamless'), ('Sheath', 'Sheath'), ('Shift', 'Shift'), ('Shirt', 'Shirt'), ('Sleep bra', 'Sleep bra'), ('Slit', 'Slit'), ('Soft cup', 'Soft cup'), ('Sports', 'Sports'), ('Strapless', 'Strapless'), ('Strapless', 'Strapless'), ('Sun', 'Sun'), ('T-Shirt', 'T-Shirt'), ('Tent', 'Tent'), ('Thong', 'Thong'), ('Trapezoid', 'Trapezoid'), ('Triangle', 'Triangle'), ('Tunic', 'Tunic'), ('Underwire', 'Underwire'), ('V-line', 'V-line'), ('Wired', 'Wired'), ('Wrap', 'Wrap'), ('Yoke', 'Yoke')], default=('Not attributed', 'Not attributed'), help_text="The product's main category", max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Black', 'Black'), ('Beige', 'Beige'), ('Camel', 'Camel'), ('Charcoal', 'Charcoal'), ('Cream', 'Cream'), ('Green', 'Green'), ('Grey', 'Grey'), ('Marine', 'Marine'), ('Navy', 'Navy'), ('Red', 'Red'), ('Taupe', 'Taupe'), ('White', 'White'), ('Yellow', 'Yellow')], default='Black', help_text='Product available colors', max_length=100),
        ),
    ]
