# Generated by Django 5.0.4 on 2024-05-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='shop_produc_name_21f200_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Prints', 'Prints'), ('Black', 'Black'), ('Beige', 'Beige'), ('Camel', 'Camel'), ('Charcoal', 'Charcoal'), ('Cream', 'Cream'), ('Green', 'Green'), ('Grey', 'Grey'), ('Kaki', 'Kaki'), ('Marine', 'Marine'), ('Navy', 'Navy'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Red', 'Red'), ('Taupe', 'Taupe'), ('White', 'White'), ('Yellow', 'Yellow')], default='Black', help_text='Product available colors', max_length=100),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(condition=models.Q(('is_main_image', True)), fields=['is_main_image'], name='main_image_images'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('on_sale', True)), fields=['on_sale'], name='on_sale_products'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(condition=models.Q(('display_new', True)), fields=['display_new'], name='display_new_products'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('unit_price__gt', 0)), name='unit_price_over_zero'),
        ),
    ]
