# Generated by Django 5.0.6 on 2024-07-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_product_unique_name_with_color_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_name_with_color',
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Print', 'Print'), ('Black', 'Black'), ('Beige', 'Beige'), ('Brown', 'Brown'), ('Camel', 'Camel'), ('Charcoal', 'Charcoal'), ('Cream', 'Cream'), ('Green', 'Green'), ('Grey', 'Grey'), ('Kaki', 'Kaki'), ('Marine', 'Marine'), ('Navy', 'Navy'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Red', 'Red'), ('Taupe', 'Taupe'), ('White', 'White'), ('Yellow', 'Yellow')], default='Black', help_text='Product available colors', max_length=100),
        ),
    ]
