# Generated by Django 5.1.4 on 2025-04-26 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('variants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_sent', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='variants.size')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=20)),
                ('total', models.DecimalField(blank=True, decimal_places=2, help_text='The total value of the stock', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='variants.size')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('is_active', True)), fields=['is_active'], name='active_stocks'), models.Index(condition=models.Q(('quantity__gte', 10)), fields=['quantity'], name='high_stock'), models.Index(condition=models.Q(('quantity__lte', 10)), fields=['quantity'], name='low_stock')],
            },
        ),
    ]
