# Generated by Django 5.1.4 on 2025-02-25 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Isle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(max_length=5)),
                ('description', models.CharField(blank=True, help_text='Describe what the isle contains', max_length=200, null=True)),
                ('total_capacity', models.PositiveIntegerField(default=1)),
                ('created_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=20)),
                ('total', models.DecimalField(blank=True, decimal_places=2, help_text='The total value of the stock', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('is_active', True)), fields=['is_active'], name='active_stocks'), models.Index(condition=models.Q(('quantity__gte', 10)), fields=['quantity'], name='high_stock'), models.Index(condition=models.Q(('quantity__lte', 10)), fields=['quantity'], name='low_stock')],
            },
        ),
    ]
