# Generated by Django 5.1.7 on 2025-03-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stockalert_delete_isle'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockalert',
            name='alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockalert',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
