# Generated by Django 6.0.3 on 2026-05-10 18:49

import discounts.validators
import django.core.validators
import django.utils.timezone
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('products', models.JSONField(blank=True, default=list, help_text='List of product ids that the discount can be applied to', null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message=None)])),
                ('percentage', models.PositiveIntegerField(default=0, validators=[discounts.validators.validate_percentage])),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
