# Generated by Django 5.1.4 on 2025-04-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.CharField(help_text="Unique session identifier for the user's carts", max_length=400),
        ),
    ]
