# Generated by Django 5.0.6 on 2024-12-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_cart_cart_price_5994ec_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_reference',
            field=models.CharField(blank=True, help_text='The customer order which can be used to link a cart item to an order', max_length=100, null=True),
        ),
    ]
