# Generated by Django 5.0.6 on 2024-12-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_order_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_reference',
            field=models.CharField(blank=True, help_text='A customer order reference which can be used to link a cart item to an order', max_length=100, null=True),
        ),
    ]
