# Generated by Django 6.0.3 on 2026-03-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collection", "0006_alter_collection_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="category",
            field=models.CharField(
                choices=[
                    ("Accessories", "Accessories"),
                    ("Activewear", "Activewear"),
                    ("Bags", "Bags"),
                    ("Bras", "Bras"),
                    ("Denim", "Denim"),
                    ("Dresses", "Dresses"),
                    ("Pants", "Pants"),
                    ("Panties", "Panties"),
                    ("Shoes", "Shoes"),
                    ("Skirts", "Skirts"),
                    ("Shorts", "Shorts"),
                    ("Suits", "Suits"),
                    ("Tops", "Tops"),
                    ("Not attributed", "Not Attributed"),
                    ("Other", "Other"),
                ],
                default="Shorts",
                help_text="Global category for the given collection",
                max_length=100,
            ),
        ),
    ]
