# Generated by Django 5.1.4 on 2025-08-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalbusiness',
            name='company_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='B', help_text="'A' for commerce, 'B' for company", max_length=2),
        ),
    ]
