# Generated by Django 5.2.9 on 2025-12-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ecommerce", "0007_alter_legalbusiness_company_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalbusiness",
            name="company_type",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B")],
                default="B",
                help_text="'A' for commerce, 'B' for company",
                max_length=2,
            ),
        ),
    ]
