# Generated by Django 5.2.10 on 2026-01-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ecommerce", "0009_alter_legalbusiness_company_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalbusiness",
            name="company_type",
            field=models.CharField(
                choices=[("A", "A"), ("B", "B")],
                default="B",
                help_text="'A' for commerce, 'B' for company",
                max_length=2,
            ),
        ),
    ]
