# Generated by Django 6.0.3 on 2026-05-10 18:49

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('stripe_charge', models.CharField(help_text='The stripe order reference or charge e.g. ch_1234', max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('Lille', 'Lille'), ('Paris', 'Paris')], default='Lille', max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('France', 'France'), ('Guadeloupe', 'Guadeloupe'), ('Martinique', 'Martinique'), ('Monaco', 'Monaco'), ('Réunion', 'Reunion')], default='France', max_length=100)),
                ('total', models.FloatField(default=0.0)),
                ('notes', django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=5000, null=True)),
                ('completed', models.BooleanField(default=False, help_text='Indicates that the order was fully completed: packaged, shipped and received by the customer')),
                ('refund_requested', models.BooleanField(default=False, help_text='Indicates that the order was cancelled and refund was requested')),
                ('stock_updated', models.BooleanField(default=False, help_text='Flag that prevents multiple updates of a stock instance with the same customer order reference')),
                ('return_delay', models.DateTimeField(blank=True, help_text='Date until which the customer can request a return', null=True)),
                ('max_return_delay', models.DateTimeField(blank=True, help_text='Maximum date until which the customer can request a return', null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customer order',
                'verbose_name_plural': 'customer orders',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField(blank=True, help_text='Active reference to the product in the catalog and which points to myshop.shop.Product ID field', null=True)),
                ('serialized_data', models.JSONField(default=dict, help_text='Serialized product data')),
                ('unit_price', models.FloatField(default=0.0, help_text='Price at the time of order')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('customer_order', models.ManyToManyField(blank=True, help_text='Link to the customer order(s)', to='orders.customerorder')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(models.Q(('stock_updated', False)), name='stock_not_updated_index'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(fields=['reference'], name='reference_index'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(models.Q(('refund_requested', True)), models.Q(('completed', True)), name='refund_requested_index'),
        ),
        migrations.AddIndex(
            model_name='customerorder',
            index=models.Index(models.Q(('completed', True)), name='completed_index'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['reference'], name='product_reference_index'),
        ),
    ]
