# Generated by Django 5.2.6 on 2025-12-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0008_remove_customerorder_products_product_customer_order_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customerorder",
            name="max_return_delay",
            field=models.DateTimeField(
                blank=True,
                help_text="Maximum date until which the customer can request a return",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customerorder",
            name="return_delay",
            field=models.DateTimeField(
                blank=True,
                help_text="Date until which the customer can request a return",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customerorder",
            name="city",
            field=models.CharField(
                choices=[("Lille", "Lille"), ("Paris", "Paris")],
                default="Lille",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="customerorder",
            name="country",
            field=models.CharField(
                choices=[
                    ("France", "France"),
                    ("Guadeloupe", "Guadeloupe"),
                    ("Martinique", "Martinique"),
                    ("Monaco", "Monaco"),
                    ("Réunion", "Reunion"),
                ],
                default="France",
                max_length=100,
            ),
        ),
    ]
