# Generated by Django 5.2.11 on 2026-02-14 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_alter_customerorder_city_alter_customerorder_country"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerorder",
            name="city",
            field=models.CharField(
                choices=[("Lille", "Lille"), ("Paris", "Paris")],
                default="Lille",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="customerorder",
            name="country",
            field=models.CharField(
                choices=[
                    ("France", "France"),
                    ("Guadeloupe", "Guadeloupe"),
                    ("Martinique", "Martinique"),
                    ("Monaco", "Monaco"),
                    ("Réunion", "Reunion"),
                ],
                default="France",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="customerorder",
            index=models.Index(fields=["reference"], name="reference_index"),
        ),
        migrations.AddIndex(
            model_name="customerorder",
            index=models.Index(
                models.Q(("refund_requested", True)),
                models.Q(("completed", True)),
                name="refund_requested_index",
            ),
        ),
        migrations.AddIndex(
            model_name="customerorder",
            index=models.Index(models.Q(("completed", True)), name="completed_index"),
        ),
    ]
