apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-depl
spec:
  selector:
    matchLabels:
      app: nuxt-app
  template:
    metadata:
      labels:
        app: nuxt-app
    spec:
      containers:
      - name: nuxt-app
        image: node:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
          name: nuxt-config
        env:
          - name: VITE_API_VERSION
            value: "2024-06-20"
          - name: VITE_STRIPE_LOCALE
            value: fr
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5173
          name: vite-port
