# Generated by Django 4.0.3 on 2022-03-08 12:52

import cart.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text="Unique item to identify each products within a user's cart", max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[cart.validators.validate_quantity])),
                ('price_pre_tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('price_post_tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_paid_for', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on', '-pk'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['price_pre_tax', 'session_id'], name='cart_cart_price_p_b49972_idx'),
        ),
    ]
