# Generated by Django 5.0.4 on 2024-05-26 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('shop', '0004_alter_product_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_cart_price_5994ec_idx',
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(condition=models.Q(('is_paid_for', True)), fields=['is_paid_for'], name='is_paid_for_carts'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='cart_price_over_zero'),
        ),
    ]
