# Generated by Django 5.0.4 on 2024-04-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_stale',
            field=models.BooleanField(default=False, help_text='Previous products from an authenticated user on which no actions were performed'),
        ),
    ]
