# Generated by Django 5.2.6 on 2025-12-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_cart_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="payment_intent",
            field=models.CharField(
                blank=True,
                help_text="Stripe payment intent ID used to identify the payment associated with this cart",
                max_length=200,
                null=True,
            ),
        ),
    ]
