# Generated by Django 4.1.3 on 2023-11-18 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
            options={
                'verbose_name': 'product history',
                'verbose_name_plural': 'product histories',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default='NPhQfnnYOSwy', max_length=100, unique=True)),
                ('stripe_reference', models.CharField(help_text='The stripe order rederence e.g. cus_1234', max_length=100, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('Lille', 'Lille'), ('Paris', 'Paris')], default='Lille', max_length=100)),
                ('zip_code', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('France', 'France'), ('Guadeloupe', 'Guadeloupe'), ('Martinique', 'Martinique'), ('Monaco', 'Monaco'), ('Réunion', 'Reunion')], default='France', max_length=100)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, to='orders.producthistory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'customer order',
                'verbose_name_plural': 'customer orders',
                'ordering': ['created_on'],
            },
        ),
    ]
