# Generated by Django 5.0.6 on 2024-07-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The total value of the stock', max_digits=5, null=True),
        ),
    ]
