apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-depl
spec:
  selector:
    matchLabels:
      app: nuxt-app
  template:
    metadata:
      labels:
        app: nuxt-app
    spec:
      volumes:
      - name: shop-store-storage
        persistentVolumeClaim:
          claimName: django-pvc
      containers:
      - name: nuxt-app
        image: node:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: VITE_STRIPE_PUBLISHABLE_KEY
            valueFrom:
              secretKeyRef:
                key: admin-secret
                name: admin-Secret
          - name: VITE_STRIPE_ACCOUNT
            valueFrom:
              secretKeyRef:
                key: admin-secret
                name: admin-Secret
          - name: VITE_API_VERSION
            value: "2024-06-20"
          - name: VITE_STRIPE_LOCALE
            value: fr
          - name: VITE_DEVELOPMENT_API_URL
            valueFrom:
              configMapKeyRef:
                key: development_api_url
          - name: VITE_PRODUCTION_API_URL
            valueFrom:
              configMapKeyRef:
                key: production_api_url
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5173
          name: vite-port
